version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.7
      - test-3.3
      - test-3.4
      - test-3.5
      - test-3.6
      - test-3.7
test-template: &test-template
  steps:
    - checkout
    - run:
        name: install requirements
        command: |
          sudo pip install --upgrade pip setuptools virtualenv;
          virtualenv env;
          source ./env/bin/activate;
          pip install -r test-requirements.txt;
          if [[ "$CIRCLE_JOB" != "test-3.3" ]] && [[ "$CIRCLE_JOB" != "test-3.4" ]]; then
            pip install -r consul-requirements.txt;
          fi;
          python setup.py install;
          pip freeze
    - run:
        name: run tests
        command: |
          mkdir test-reports;
          if [[ "$CIRCLE_JOB" == "test-2.7" ]]; then
            pytest -s --cov=ldclient --junitxml=test-reports/junit.xml testing;
            sh -c '[ -n "${CODECLIMATE_REPO_TOKEN+1}" ] && codeclimate-test-reporter || echo "No CODECLIMATE_REPO_TOKEN value is set; not publishing coverage report"';
          else
            pytest -s --junitxml=test-reports/junit.xml testing;
          fi
    - run:
        name: test packaging/install
        command: ./scripts/test-packaging.sh
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: test-reports

jobs:
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-jessie
      - image: redis
      - image: amazon/dynamodb-local
      - image: consul
  test-3.3:
    <<: *test-template
    docker:
      - image: circleci/python:3.3-jessie
      - image: redis
      - image: amazon/dynamodb-local
      # python-consul doesn't support Python 3.3
  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4-jessie
      - image: redis
      - image: amazon/dynamodb-local
      # python-consul doesn't support Python 3.4
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie
      - image: redis
      - image: amazon/dynamodb-local
      - image: consul
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-jessie
      - image: redis
      - image: amazon/dynamodb-local
      - image: consul
  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch
      - image: redis
      - image: amazon/dynamodb-local
      - image: consul
